### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by thatch** [comment]
This is the [second time](https://github.com/facebookincubator/Bowler/blob/master/CONTRIBUTING.md#getting-started) this style of Makefile has been edited to use `$(PYTHON)` in the lower piece so I think I'm missing something about what workflows people are used to.  How do you typically develop out of a repo?

When you activate a virtualenv on windows, does it add python to the head of the path?  This is modeled after the [workflow for Bowler](https://github.com/facebookincubator/Bowler/blob/master/CONTRIBUTING.md#getting-started).  @jreese is probably interested in the outcome of this discussion.

```
PYTHON=python3 make venv
source .venv/bin/activate (or equivalent, depending on shell)
# now 'python' is the venv python, regardless of what it started out
make test
```

Are you doing something more like this, without activating?

```
PYTHON=python3 make venv
PYTHON=.venv/bin/python make test
```

**Comment by jayvdb** [comment]
I dont use venvs if I can avoid it.  If a package can not co-exist with any another package I use, I consider that to be a bug in one of them, and I try to fix it.

**Comment by thatch** [comment]
I assume on Windows you have a `python` that is 3.x and no `python3`?  I have the same problem on Fedora, would something like (untested)

```
PYTHON?=$(firstword $(shell which python3 python 2>/dev/null))
```

work for a non-platform-specific guessing?  Or are there typically spaces in the path?

The rest of the change is fine.

BTW this file is generated by https://github.com/python-packaging/skel/blob/master/templates/Makefile.in and we should make a similar change there to eventually propagate to my other projects.

**Comment by jayvdb** [comment]
Your suggestion would work fine for me, but I dont use Windows.  The Makefile change is also a bit of a throwaway change for me - I can work without the Makefile, or I can set PYTHON=.. , so happy to remove the OS specific improvements which cause you concern.

Windows has spaces everywhere to frustrate everyone.  On Windows CI, I often encounter `sys.executable` containing spaces because it was installed in a directory path with spaces, and thus needing quoting before it can be used with `subprocess`.  I havent checked whether this occurs on this repos Azure setup.

**Comment by jayvdb** [comment]
I've removed the OS-detection and handling of `PYTHON`.

**Pull request merged**
